# Generated by Django 3.2.9 on 2021-11-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='phone',
            field=models.IntegerField(default=0, verbose_name='Phone number'),
        ),
    ]
