# Generated by Django 3.2.9 on 2021-11-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='phone',
            field=models.IntegerField(default=0, verbose_name='Phone number'),
        ),
    ]
