# Generated by Django 3.2.9 on 2021-11-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211115_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('phone', models.IntegerField(default=0, verbose_name='Phone number')),
                ('email', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
